# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "kitchen-ai" # Replace with your app name
primary_region = "lax" # Los Angelas

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "pnpm run migrate"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  # These will use the Electric Cloud and external Postgres you configure

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[checks]
  [checks.alive]
    type = "http"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/api/health"
    protocol = "http"
    [checks.alive.headers]
