[build]
  publish = "dist"
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = ".netlify/functions-internal"

# Environment variables (will be set via Netlify dashboard)
# DATABASE_URL
# SOURCE_SECRET
# OPENAI_API_KEY
# NEON_API_KEY
# VITE_CLERK_PUBLISHABLE_KEY
# ELECTRIC_URL
# SOURCE_ID
