/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ELECTRIC_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ELECTRIC_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENAI_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PGURI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PGURI_POOL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "kitchen-ai-site": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "kitchen-ai-worker": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}